import { useState, useEffect } from "react";
import { ethers } from 'ethers'
import { Row, Col, Card, Button, Form} from 'react-bootstrap'

const toWei = (num) => ethers.utils.parseEther(num.toString())

const Home = ({ nft, nftRead, account}) => {

    const [mintAmount, setMintAmount] = useState(0)
    const [message, setMessage] = useState('')
    const [nftCount, setNftCount] = useState(0)
    const [loading, setLoading] = useState("not loaded")

    const mintNFT = async (mintAmount) => {

        if(mintAmount = 0) {
            setMessage("Please enter a valid amount")
        }
        if(account === null) {
            setMessage("Please connect wallet before minting")
        } else {
            //Fetch nft price
            const mintPrice = await nftRead.mintPrice()
            console.log("Mint price: ", mintPrice)
            //mint the nfts
            await (await nft.mint(mintAmount, { value: mintPrice})).wait()
            //display nfts minted
        }
    }

    const getData = async () => {
        const tokenCount = await nftRead.tokenCount()
        setNftCount(tokenCount.toNumber())
        setLoading("loaded")
    }


    useEffect(async () =>{
        getData()
    },[nft, nftRead])

    return(
        <div>
            <h1><b>InspiroNFT</b></h1>
            <Card className="mx-auto" style={{ width: '70rem' }}>
                <Card.Body className="card-text-center">
                    <Card.Text>
                        An NFT collection based on random inspirational quotes generated by InspiroBot.
                    </Card.Text>
                    <Card.Text>
                        This project has been made for entertainment purposes only. {loading}
                    </Card.Text>

                    <h2><b>NFTs Minted:</b></h2>
                    <h1><b>{nftCount}/1000</b></h1>

                    <Card className="mx-auto" style={{ width: '50rem' }}>
                        <Card.Header>
                            <h4><b>Mint new NFTs!</b></h4>
                        </Card.Header>
                        <Card.Body>
                            <Form className="mx-auto" style={{ width: '30rem' }}>
                                Amount to Mint:
                                <Form.Control onChange={(e) => setMintAmount(e.target.value)} 
                                    required type="number" min="1" placeholder="Enter amount" />
                                <br></br>
                                Mint Price: 10 MATIC Each
                                <br></br>
                                <br></br>
                                <Button onClick={() => mintNFT(mintAmount)} variant="primary" type="submit" size="lg">
                                    Mint
                                </Button>
                                <p style={{color: 'red', fontSize:"12px"}}>{message}</p>
                            </Form>
                        </Card.Body>
                    </Card>
                </Card.Body>
            </Card>
            <i>Note: This site is still a work in progress</i>
            
        </div>
    )
}

export default Home;